#!/bin/bash

phoenix_config=/opt/phoenix/config/phoenix_config.txt
install_path=/opt/phoenix/bin
install_target=phMonitorSupervisor

if [[ ! -f $phoenix_config ]]; then
  echo "Unable to locate $phoenix_config"
  exit 1
fi

phRole=$(grep MON_ROLE "$phoenix_config" | cut -f2 -d=)
if [[ $phRole != "$install_target" ]]; then
  echo "Installation on $phRole is not advised.  Please only install on a supervisor"
  exit 1
fi

source_dir=$(dirname "$(readlink -f "$0")")

dos2unix "$source_dir"/es_*
chmod +x "$source_dir"/es_*
cp -f "$source_dir"/es_* "$install_path"

packages=($(ls -1 "$source_dir"/packages))

for package in ${packages[@]}; do
	rpm --quiet -q "${package%.rpm}" || rpm --quiet -i "${source_dir}/packages/${package}"
done

echo "Installation Complete!"
ls "$install_path"/es_*
